### ISSUE TITLE
Hi! Change your password :)

### ISSUE THREAD

**Issue by soko1** [heidsoft/HeidBook#1]
Hi! Change your password https://github.com/heidsoft/HeidsoftNote/blob/fd811af4201b4c0ef43ee1e876b0437959359a59/linux/msmtp%E9%85%8D%E7%BD%AE.txt and use option:

passwordeval    gpg2 -d -q --for-your-eyes-only --no-tty  ~/.passwd.gpg 

:)

**Comment by heidsoft** [comment]
thanks,这个邮箱没用了
